Gabriele-Zini/bool-bnb-backend-final-project

database/migrations/2024_02_16_154329_create_apartments_table.php
database/migrations/2024_02_16_154419_create_messages_table.php
database/migrations/2024_02_16_154540_create_services_table.php
database/migrations/2024_02_16_154618_create_apartment_service_table.php
database/migrations/2024_02_16_154713_create_apartment_info_table.php
database/migrations/2024_02_16_154742_create_sponsorships_table.php
database/migrations/2024_02_16_154817_create_apartment_sponsorship_table.php
database/migrations/2024_02_16_154858_create_views_table.php

1 makemigration

---

database/migrations/2024_02_16_154419_create_messages_table.php
database/migrations/2024_02_16_154540_create_services_table.php
database/migrations/2024_02_16_154618_create_apartment_service_table.php

4 add messages services and apartment services table

---

database/migrations/2014_10_12_000000_create_users_table.php
database/migrations/2024_02_16_154329_create_apartments_table.php
database/migrations/2024_02_16_154858_create_views_table.php

3 add users and apartments table

---

database/migrations/2024_02_16_154713_create_apartment_info_table.php
database/migrations/2024_02_16_154742_create_sponsorships_table.php
database/migrations/2024_02_16_154817_create_apartment_sponsorship_table.php

add: apartment_info, sponsorship and apartment_sponsorship migrations

---

database/migrations/2024_02_16_154419_create_messages_table.php
database/migrations/2024_02_16_154618_create_apartment_service_table.php

fix: spelling error on messages

---

database/seeders/MessagesTableSeeder.php
database/seeders/ServicesTableSeeder.php

add: Messages and Services seeders

---

database/seeders/Apartment_infoTableSeeder.php
database/seeders/ApartmentsTableSeeder.php

add: apartments table seeder

---

database/migrations/2024_02_16_154713_create_apartment_infos_table.php
database/seeders/ApartmentsTableSeeder.php

add: apartment_info seeder

---

database/seeders/MessagesTableSeeder.php

fix: apartments foreign key

---

database/seeders/SponsorshipsTableSeeder.php
database/seeders/ViewsTableSeeder.php

16 add seeders for sponsorships and views tables

---

app/Http/Controllers/Admin/ApartmentController.php
app/Models/Sponsorship.php
database/seeders/ApartmentsTableSeeder.php
resources/views/admin/apartments/create.blade.php
resources/views/admin/apartments/index.blade.php
resources/views/layouts/app.blade.php
resources/views/layouts/navigation.blade.php
routes/web.php

24 add crud operation wip

---

app/Http/Controllers/Admin/ApartmentController.php

add: sorting to countryCodes

---

app/Http/Controllers/Admin/ApartmentController.php
database/migrations/2024_02_16_154329_create_apartments_table.php
resources/views/admin/apartments/create.blade.php
resources/views/layouts/app.blade.php

28 crud store wip

---

app/Http/Controllers/Admin/ApartmentController.php
app/Models/Apartment.php
database/migrations/2024_02_16_154713_create_apartment_infos_table.php
database/seeders/ApartmentsTableSeeder.php
resources/js/app.js
resources/views/admin/apartments/create.blade.php
resources/views/admin/apartments/edit.blade.php
resources/views/admin/apartments/index.blade.php
resources/views/admin/apartments/show.blade.php

31 add apartment info to create

---

app/Http/Controllers/Admin/ApartmentController.php
app/Models/Apartment.php
database/migrations/2024_02_16_154329_create_apartments_table.php
database/seeders/ApartmentsTableSeeder.php
package-lock.json
package.json
resources/js/app.js
resources/scss/app.scss
resources/views/admin/apartments/create.blade.php
resources/views/admin/apartments/index.blade.php
resources/views/admin/apartments/show.blade.php
resources/views/layouts/app.blade.php
resources/views/layouts/guest.blade.php

33 test branch

---

app/Http/Controllers/Admin/ApartmentController.php
resources/views/admin/apartments/edit.blade.php

add: images in edit and update

---

app/Http/Controllers/Admin/MessageController.php
config/messages.php
database/migrations/2024_02_16_154419_create_messages_table.php
database/seeders/MessagesTableSeeder.php
resources/views/admin/apartments/show.blade.php
resources/views/admin/messages/index.blade.php
resources/views/admin/messages/show.blade.php
routes/web.php

55 add messages backoffice output

---

app/Http/Controllers/Admin/ApartmentController.php
app/Http/Controllers/Admin/ImageController.php
app/Models/Image.php
database/migrations/2024_02_21_124549_create_images_table.php
package-lock.json
package.json
resources/js/app.js
resources/scss/app.scss
resources/views/admin/apartments/create.blade.php
resources/views/admin/apartments/edit.blade.php
resources/views/admin/apartments/index.blade.php
resources/views/admin/apartments/show.blade.php
resources/views/admin/images/index.blade.php

53 add sorting images and output on edit

---

app/Http/Controllers/Api/MessageController.php
routes/api.php

65 add messages api

---

config/apartments.php
config/users.php
database/seeders/ApartmentsTableSeeder.php
database/seeders/DatabaseSeeder.php
database/seeders/UsersTableSeeder.php

67 refactoring seeders

---

app/Http/Controllers/Api/ApartmentController.php

71 query for sponsored results

---

app/Http/Controllers/Admin/SponsorshipController.php

fix: check data and hours to set a sponsorship

---

app/Http/Controllers/Admin/MessageController.php
resources/views/admin/messages/all.blade.php
resources/views/layouts/navigation.blade.php
routes/web.php

72 views on messages and sponsosrships divided by apartments for each account

---

app/Http/Controllers/Admin/SponsorshipController.php
resources/views/admin/braintree.blade.php
resources/views/admin/sponsorships/all.blade.php
resources/views/layouts/navigation.blade.php
routes/web.php

81 sponsorships all

---

resources/scss/app.scss
resources/views/admin/apartments/create.blade.php
resources/views/admin/apartments/edit.blade.php
resources/views/admin/apartments/index.blade.php
resources/views/admin/apartments/show.blade.php
resources/views/admin/messages/all.blade.php
resources/views/admin/messages/index.blade.php
resources/views/admin/messages/show.blade.php
resources/views/layouts/navigation.blade.php

Add: style on pages

---

resources/js/app.js
resources/views/admin/braintree.blade.php

91 change url of payment page

---

resources/scss/app.scss
resources/views/admin/messages/all.blade.php
resources/views/dashboard.blade.php

Update: style-messages
